services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    KJanczyk\PimcoreSOMLBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
