services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    KJanczyk\PimcoreSOMLBundle\Command\:
        resource: '../src/Command/*'
        tags: [ 'console.command' ]
